# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        # node versions
        node-version: [16.x] 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2

      # Use the node version specified in strategy
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}

      # Install packages
      - name: Install node packages
        run: rm -rf node_modules && yarn install --frozen-lockfile
        
      # Build optimized production build
      - name: Production build
        run: yarn run build --if-present

      # Run tests 
      - name: Run Tests
        run: yarn run test

      # Deploy to AWS S3 server
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with: 
          args: --follow-symlinks --delete
          # args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
          
